# Week 2 Assignment: NumPy & Pandas for Data Analytics


## 🎯 Objective

The objective of this assignment is to develop practical skills in NumPy and Pandas, which are essential Python libraries for Data Analytics. Students will learn to work with arrays, perform mathematical and statistical operations, manipulate datasets, inspect and clean data, filter and sort records, combine datasets, perform GroupBy and Pivot Table operations, and export processed data.


Task 1: NumPy & Arrays

Create a Python program using NumPy that:
Imports NumPy.
Creates a NumPy array containing at least 10 numbers.
Displays the array.
Displays the array's shape, size, and data type.
Creates a one-dimensional and two-dimensional array.

In [2]:
import numpy as np

In [13]:
list01 = [1,2,3,4,5]
list02 = [6,7,8,9,10]
list03 = [11,12,13,14,15]
arr_list01 = np.array([list01, lisr02, list03])
print(arr_list01)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [14]:
print("Shape: ", arr_list01.shape)
print("Size: ", arr_list01.size)
print("Data Type: ", arr_list01.dtype)

Shape:  (3, 5)
Size:  15
Data Type:  int64


In [19]:
list_a = [4,6,8]
arr_a = np.array([list_a])
print(arr_a, "This is 1-D Array.")

[[4 6 8]] This is 1-D Array.


In [20]:
list_b = [0,3,6]
arr_b = np.array([list_b])
print([list_a, arr_b], "This is 1-D Array.")

[[4, 6, 8], array([[0, 3, 6]])] This is 1-D Array.
